language: node_js

services:
  - docker

install:
  - cp .env.example .env
  - docker-compose build --build-arg UID=$(id -u) --build-arg GID=$(id -g) node
  - docker-compose run --rm node npm ci

script:
  - docker-compose run --rm node npm run build-server
  - docker-compose run --rm node npm test
  - docker-compose run --rm node npm run build
  # check that dist contains the latest build result
  - git status && git diff-index --quiet HEAD dist/

notifications:
  email:
    on_success: never
