language: node_js

services:
  - docker

install:
  - cp .env.example .env
  - docker-compose run --rm node npm ci

script:
  - docker-compose run --rm node npm run build-server
  - docker-compose run --rm node npm run lint
  - docker-compose run --rm node npm run test

notifications:
  email:
    on_success: never
