version: '2'

services:
  node:
    build:
      context: ./
    image: wmde/wikibase-termbox-node
    volumes:
      - '~/.npm:/.npm'
      - './:/app'
    working_dir: /app
    environment:
      - NODE_ENV

  csr:
    extends:
      service: node
    ports:
      - '${CSR_PORT}:8080'
    command: 'npm run-script serve'

  ssr:
    extends:
      service: node
    ports:
      - '${SSR_PORT}:${SSR_PORT}'
    command: 'npm run dev-server'
    external_links:
      - 'nginx-proxy:default.web.mw.localhost'
    networks:
      mediawiki_dev_network:
        aliases:
          - 'node-ssr'
      default: ~

networks:
  mediawiki_dev_network:
    external:
      name: '${MEDIAWIKI_NETWORK_TO_JOIN}'
